name: Build

on:
  push:
    branches: [ master ]

jobs:
  testaction:
    runs-on: ubuntu-latest
    name: Build TypeScript and publish to release
    steps:
      - name: â³ Checkout
        uses: actions/checkout@v2
      - name: ğŸ’¿ Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: ğŸš€ Build
        run: |
          npm ci
          npm run build
      - name: ğŸŒ Release (using local code)
        uses: ./
        id: release-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: 'v0.0-rolling'
          asset-name: 'index.js'
          file: 'dist/index.js'
      - name: ğŸŒ Release (using published action)
        uses: djnicholson/release-action@v2.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: 'v2.8-candidate'
          release-name: 'Rolling build'
          asset-name: 'index.js'
          file: 'dist/index.js'
